---
- name: add docker apt key
  apt_key: >
    id=58118E89F3A912897C070ADBF76221572C52609D
    keyserver=hkp://p80.pool.sks-keyservers.net:80
    state=present

- name: add docker apt repository
  apt_repository: >
    repo="deb https://apt.dockerproject.org/repo ubuntu-trusty main"
    state=present
    update_cache=yes

- name: Check Docker
  apt: name=docker state=latest
  become: true

- name: install docker and requirements
  apt: update_cash=yes
  apt: name=docker-engine state=present
  
- name: Install docker-py
  pip: name=docker-py executable=/usr/local/bin/pip
  become: true

- name: configure docker
  copy: content='DOCKER_OPTS=""'
     dest=/etc/default/docker
  notify: restart docker

- name: install required python packages for ansible and docker
  apt: pkg= {{ item }} state=latest
  with_items:
    - python-pip
    - python-dev
