---
- name: Create a Prometheus container
  docker_container:
    user: root
    name: prometheus
    image: prom/prometheus
    state: started
    hostname: prometheus
    ports: 
      - 9090:9090
    volumes:
      - /data/monitoring/prometheus:/prometheus
      - ./prometheus:/etc/prometheus
    privileged: true
    restart: yes