---
- name: Create a PHP container
  docker_container:
    user: root
    name: php
    image: bitnami/php-fpm:latest
    state: started
    hostname: php
#    links:
#      - web
    ports: 
      - 9090:9000
    volumes:
      - ./code:/code
    privileged: true
#    recreate: yes
    restart: yes