---
- name: Create a PHP container
  docker_container:
    user: root
    name: php
    image: bitnami/php-fpm:latest
    state: started
    hostname: php
    networks:
      - app-tier
    links:
      - web
    ports: 
      - 9090:9090
    volumes:
      - ./code:/var/www/html/site
    privileged: true