---
- name: Create a Grafana container
  docker_container:
    user: root
    name: grafana
    image: grafana/grafana
    state: started
    hostname: grafana
    ports: 
      - 3000:3000
    env:
      GF_SECURITY_ADMIN_PASSWORD=1234567
      GF_SECURITY_ADMIN_USER=admin
    volumes:
      - /data/monitoring/grafana:/var/lib/grafana
    privileged: true
    restart: yes