---
- name: Create a network
  docker_network:
    name: apptier
    ipam_options:
      subnet: 172.18.0.1/16
      gateway: 172.18.0.1
    connected:
          - web
          - php
          - mysql_db
    force: yes
