global:
  smtp_smarthost: 'smtp:25'
  smtp_from: 'root@smtp'
  smtp_auth_username: 'admin@smtp'
  smtp_auth_password: '12345'
  smtp_require_tls: false
route:
  group_by: ['alert']
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 1h
  receiver: prometheus-alerts
  routes:
  - match:
      job: prometheus
    receiver: prometheus-alerts
    repeat_interval: 1h
receivers:
- name: 'prometheus-alerts'
  email_configs:
  - to: 'dk-fan90@i.ua'
    send_resolved: true
    require_tls: false