---
- name: Create SMTP container
  docker_container:
    user: root
    name: smtp
    image: namshi/smtp
    state: started
    hostname: smtp
    ports: 
      - 25:25
    privileged: true
    restart: yes