---
- hosts: all
  become: yes
  
  roles:
    - install_docker
    - config_prom
    - config_node-expr
    - config_graf
    - config_cadv
    - config_alert
    - config_mail
    - connect_to_network
