Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "10.1.0.112", guest: 80, host: 9090
  config.vm.hostname = "srv00mntr"

#####################################
config.vm.provision "shell", inline: <<-SHELL
   apt-get -y update
   apt-get install -y device-mapper-persistent-data
   apt-get install -y lvm2
SHELL
  
#####################################
# Run Ansible from the Vagrant VM
config.vm.provision "ansible_local" do |ansible|
  ansible.playbook = "playbook.yml"
  ansible.limit = "all"
  ansible.become = true
  ansible.install_mode = "pip"
#  ansible.provisioning_path = ""
  ansible.verbose = "vvv"
end
end
