---
- hosts: all
  become: yes
  
  roles:
    - install_docker
    - config_cont_php
    - config_cont_nginx
    - config_cont_mysql
    - monitor_node
    - monitor_cadvisor
    - connect_to_network
