---
- name: Create a Jenkins container
  docker_container:
    user: root
    name: jenkins
#    image: jenkins/jenkins
    state: started
    hostname: jenkins
    ports: 
      - 50000:50000
      - 8080:8080
      - 33011:33011
    privileged: true
    restart: yes