---
- name: Create a network and connect containers
  docker_network:
    name: apptier
    ipam_options:
      subnet: 172.2.0.1/16
      gateway: 172.2.0.1
    connected:
          - prometheus
          - node-expr
          - grafana
          - cadvisor
          - alertmanager
          - smtp
    force: yes