global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'monitoring'
rule_files:
  - "alert.rules"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - prometheus:9090
        labels:
          __metrics_path__: /metrics
          name: prometheus
      - targets:
        - node-expr:9100
        labels:
          name: server-node-exporter
      - targets:
        - cadvisor:8080
        labels:
          name: server-cadvisor

  - job_name: 'prometheus-client'
    static_configs:
      - targets:
        - 10.1.0.111:9100
        labels:
          name: client-node-exporter
      - targets:
        - 10.1.0.111:8081
        labels:
          name: client-cAdvisor
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093