---
- name: Create a NGINX container
  docker_container:
    user: root
    name: web
    image: nginx:latest
    state: started
    hostname: web
    networks: apptier 
    ports: 
      - 8080:80
      - 4433:443
    volumes:
      - ./code:/var/www/html/site
      - ./site.conf:/etc/nginx/conf.d/site.conf:ro
    privileged: true

