---
- name: Create a NGINX container
  docker_container:
    user: root
    name: web
    image: nginx:latest
    state: started
    hostname: web
    ports: 
      - 8080:80
    volumes:
      - ./code:/code
      - ./conf/site.conf:/etc/nginx/conf.d/site.conf/
    privileged: true
    restart: yes

