---
- name: Create a NGINX container
  docker_container:
    user: root
    name: web
    image: nginx:latest
    state: started
    hostname: web
    ports: 
      - 8080:80
    volumes:
      - ./php:/var/www/html
      - ./conf/site.conf:/etc/nginx/conf.d/default.conf
#    command: rm /etc/nginx/conf.d/default.conf 
    privileged: true
#    recreate: yes
    restart: yes

