# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  #  config.vm.network "private_network", ip: "192.168.33.100"
  config.vm.hostname = "srv02web-db"

#####################################
config.vm.provision "shell", inline: <<-SHELL
   apt-get -y update
   apt-get install -y yum-utils
   apt-get install -y device-mapper-persistent-data
   apt-get install -y lvm2
#   yum-config-manager --add-repo "$DOCKERURL/centos/docker-ee.repo"
SHELL
  
#####################################
# Run Ansible from the Vagrant VM
config.vm.provision "ansible_local" do |ansible|
  ansible.playbook = "playbook.yml"
  ansible.sudo= true
  ansible.install_mode = "pip"
#  ansible.provisioning_path = "c:\Users\Yurii_Honcharenko\test_proj\.sys01-fb\"
  ansible.verbose = "vvv"

end
end
